### PR TITLE
Accept --set cli options and pass directly to helm

### PR DESCRIPTION
**Pull request by erkolson**
You might consider this an anit-pattern in your usage but I'd like a simple way to invoke autohelm from ci/cd but pass a parameter to change a value like an image tag for instance.  If there is another way to do this, I'd like to hear what you are doing.

Making sure the version controlled values for a specific `course` get updated would be out of band but could be incorporated into autohelm as well.

### CODE REVIEW

**Comment by sudermanjr** [comment]
I'm curious about your desired use-case for this feature.  You are correct that this would generally be considered an anti-pattern.  In addition, would something like what was proposed in #49 be sufficient?

**Comment by erkolson** [comment]
#49 does look like it would be sufficient for my needs.

The use case is for a centralized CI/CD server to be able to select from a collection of artifact builds and deploy to one of many environments.  The same application lives in each environment, so an autohelm course seems a sensible way to define the services in each environment.  In order to deploy new artifact builds to an environment, a value needs to be updated with the new tag name. 
 Options would be using jq/jy/sed, etc to update the `course.yaml` before executing autohelm. 

I've written something similar in the past (though do not own the IP so can not reuse now) that would parse the configuration (values) file for a given helm release, merge in any values passed with the `--set` flag then perform the `helm upgrade`.  Committing the updated value was out of band of the tool but was easily added to the CI/CD job that called the helm wrapper/runner.

**Comment by sudermanjr** [comment]
That's what I assumed was the use-case, but I wanted to make sure before I made any more assumptions.  

If #49 is sufficient, would it be possible to refactor this into that, or open a new PR?

**Comment by erkolson** [comment]
I can take a stab at it.  I should have some time tomorrow.

**Comment by ejether** [comment]
Closing this in light of the discussion on https://github.com/reactiveops/autohelm/issues/49

**Pull request closed without merging**
